### ISSUE TITLE
Issues displaying SVG icons in V2 app

### ISSUE THREAD

**Issue by abaretta** [athombv/homey-vectors-public#51] opened 2019-02-17 14:46 UTC
Hi Ivo,  

I have a couple of new icons I want to use in the OpenWeatherApp, however, I can't get them to display in the Homey app. 

https://github.com/abaretta/nu.baretta.openweathermap/tree/master/assets/images/sunrise.svg
https://github.com/abaretta/nu.baretta.openweathermap/tree/master/assets/images/sunset.svg
https://github.com/abaretta/nu.baretta.openweathermap/tree/master/assets/images/visibility.svg
https://github.com/abaretta/nu.baretta.openweathermap/tree/master/assets/images/text.svg

When testing on Android I found another icon doesn't display in the Android app:
https://github.com/abaretta/nu.baretta.openweathermap/tree/master/assets/images/wind_angle.svg.

Any chance you could have a look at these icons? I have tried converters that worked with the V1 app, and several other icons, but wasn't able to figure out why they do not display.

Thanks in advance!

**Comment by FricoRico** [comment] 2019-02-18 21:56
+1 On that, running into issues myself

**Comment by IvoDerksen** [comment] 2019-02-18 21:58
I'll have a look at it! 
I can see at first sight that visibilty.svg won't be visible since the viewport is very small, but I have to take a closer look to all of the icons. Will get back to you Wednesday or Thursday!

**Comment by abaretta** [comment] 2019-02-19 07:41
Hi Ivo, sounds good :-) 

There seem to be several different issues with the icons. Do you happen to have any reference documentation on what should and what should not be in the SVG files? Quite a few developers are running into issues with the icons at the moment.

Thanks in advance!

**Comment by edwinvdpol** [comment] 2019-02-19 09:56
Same problem over here...

**Comment by IvoDerksen** [comment] 2019-02-19 10:16
Did this all happen within a short period of time, because then it could be an issue larger than icons itself.

Are the icons literally disappearing?

The most important steps of the SVG are the viewport, or the artboard. Which should be tightly wrapped around the icon. 
And to think about it in a way of a sheet in front of the sun, there is one color, the icon can only exist out of paths consisting of that color, what must not be visible should be transparant.

@abaretta 
The wind angle has a few lines in it, which could cause it to look white striped.
Visibilty icon has the afore mentioned viewport problem.
But sunset en sunrise should work. I've attached the sunrise icon which does check my requirements.
[sunrise.zip](https://github.com/athombv/homey-vectors-public/files/2879474/sunrise.zip)

Get back at me, then I'll try to see what is going on, if it's the icons that are faulty, or the problem is higher up the chain.

**Comment by abaretta** [comment] 2019-02-19 18:43
Hi Ivo,

Thanks for the feedback. The 'wind_angle' icon displays fine on an iPhone, but doesn't display at all in the Android app.

The 'sunrise' SVG you sent doesn't display in my app, see screenshot below. It seems many developers are having issues with icons at the moment, could indeed point to a bigger issue.

![image](https://user-images.githubusercontent.com/25007256/53039063-88f82c00-347e-11e9-9e91-9862e9573ca5.png)

**Comment by IvoDerksen** [comment] 2019-02-20 09:33
Thanks for the screenshot.
Yes, indeed. The problem does look bigger than the icons.

Would you be willing to report this on:
https://github.com/athombv/homey-apps-sdk-issues/issues

I feel like there is nothing more I can do about it, I'm sorry for the inconvenience!

**Comment by abaretta** [comment] 2019-02-20 10:38
Hi Ivo,
Thanks for looking into is. Any idea why the 'wind angle' icon does display (at least in the iPhone app) while the other icons don't? And the 'clouds.svg' has no issues displaying at all (maybe a better example).

On a related note, I changed the viewport settings of the visibility icon using the settings of a 'working' icon, however it still did not display. 

Note that as a sanity check I have verified the path etc. by copying a working icon (e.g. 'clouds.svg') to 'sunrise.svg' and then I do indeed get the clouds icon displayed for the sunrise capability. BTW, 'clouds.svg' is a custom icon as well, and it works fine, also in the Android app.

Thanks!

**Comment by IvoDerksen** [comment] 2019-02-20 10:56
Was the wind angle icon already in the app? 
Something in an app update might have broken something, not sure?

As said, the icons for sunrise and sundown should work, I can't see a reason why not.

You can test this one, from a similar issue reported yesterday, regarding a display icon issue too. #52 
[Real-tux_mono.svg.zip](https://github.com/athombv/homey-vectors-public/files/2884255/Real-tux_mono.svg.zip)

I have no other ideas, sorry!

**Comment by abaretta** [comment] 2019-02-20 11:01
Hi Ivo,

Yes, the wind_angle icon was already in there, as well as the 'clouds.svg' icon. Indeed the Real-tux icon doesn't work either. I'll create the ticket and add these details, thanks!

**Comment by IvoDerksen** [comment] 2019-04-01 17:36
Closing this since it seems closed!

**Closed by IvoDerksen** 2019-04-01 17:36 UTC
